name: Run Licensing Board Scraper

on:
  schedule:
    - cron: "0 0 * * 1" # Runs at midnight every Monday
    
  workflow_dispatch: # Allows manual trigger

permissions:
  contents: write
  pull-requests: write

jobs:
  scrape:
    runs-on: ubuntu-latest
    env:
      SCRAPER_DIR: ./scraper/scrape   # App Directory
      PDFS_DIR: ./data/voting_minutes_pdfs  # PDF Output Directory

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Sync dependencies (from uv.lock)
        working-directory: ${{ env.SCRAPER_DIR }}
        run: uv sync --frozen

      - name: Run Scraper
        working-directory: ${{ env.SCRAPER_DIR }}
        run: uv run python -m app.main --download_dir ${{ env.PDFS_DIR }}

      - name: Create pull request to merge in new scraped data and PDFs
        uses: peter-evans/create-pull-request@v7
        with:
          title: "[SCRAPER] Update scraped data and PDFs"
          body: |
            Update scraped data and PDFs
            - This PR updates the scraped data and PDFs based on the latest data scraped from the Boston liquor licensing board website.\
            - Auto generated by the Licensing Board Scraper Github Action.
          branch: update-scraped-data-and-pdfs
          delete-branch: true
          commit-message: "[SCRAPER] Update scraped data and PDFs"
          committer: Github Actions <hello@codeforboston.org>
          author: Github Actions <hello@codeforboston.org>
          add-paths: |
            ${{ env.SCRAPER_DIR }}/${{ env.DFS_DIR }}/*.pdf
            ${{ env.SCRAPER_DIR }}/data/url_exclude_list.json
            ${{ env.SCRAPER_DIR }}/data/link_stats_log.csv
            ${{ env.SCRAPER_DIR }}/data/hearing_video_links.json
            ${{ env.SCRAPER_DIR }}/data/voting_minutes_links.json
            ${{ env.SCRAPER_DIR }}/log/app.log

